import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative flex h-screen overflow-hidden">
      <div className="w-[20%]">
      <Menu/>
      </div>
      <div className="w-[80%]">
        {children}
      </div>
        
        </body>
    </html>
  );
}
